name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0
      - name: get project name
        uses: jungwinter/split@v1
        id: split
        with:
          msg: ${{ github.repository }}
          seperator: '/'

      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_SECRET }}
          repository: necromant/${{ steps.split.outputs._1 }}
          tags: latest